# Generated by Django 3.2.7 on 2021-09-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referee', to='sccr.referee'),
            preserve_default=False,
        ),
    ]
