# Generated by Django 3.2.7 on 2021-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0002_match_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
