# Generated by Django 3.2.7 on 2021-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0003_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team_score',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='match_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
