# Generated by Django 3.2.7 on 2021-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0004_auto_20210923_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
