# Generated by Django 3.2.7 on 2021-09-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0005_auto_20210923_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_players_scored',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
