# Generated by Django 3.2.7 on 2021-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sccr', '0006_match_match_players_scored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_players_scored',
            new_name='match_players_goals_scored',
        ),
    ]
